name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./tracker-ui/package-lock.json
            
      - name: Install dependencies (tracker-ui)
        working-directory: ./tracker-ui
        run: npm install --legacy-peer-deps
        
      - name: Run linting
        working-directory: ./tracker-ui
        run: npm run lint:ci
        
      - name: Run unit tests
        working-directory: ./tracker-ui
        run: npm run test
        
      - name: Build project
        working-directory: ./tracker-ui
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: tracker-ui/dist/
          retention-days: 7
