// Training state action types
export const TRAINING_ACTIONS = {
  // Profile actions
  SET_PRESET: 'SET_PRESET',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  
  // Volume landmarks
  UPDATE_VOLUME_LANDMARKS: 'UPDATE_VOLUME_LANDMARKS',
  SAVE_VOLUME_LANDMARKS: 'SAVE_VOLUME_LANDMARKS',
  
  // Mesocycle actions
  SETUP_MESOCYCLE: 'SETUP_MESOCYCLE',
  UPDATE_MESOCYCLE: 'UPDATE_MESOCYCLE',
  ADVANCE_WEEK: 'ADVANCE_WEEK',
  
  // Workout actions
  START_WORKOUT: 'START_WORKOUT',
  LOG_SET: 'LOG_SET',
  UNDO_SET: 'UNDO_SET',
  FINISH_WORKOUT: 'FINISH_WORKOUT',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',
  SEED_MOCK_DATA: 'SEED_MOCK_DATA',
  
  // Deload actions
  ANALYZE_DELOAD: 'ANALYZE_DELOAD',
  INITIALIZE_AT_MEV: 'INITIALIZE_AT_MEV',
  
  // Intelligence actions
  INITIALIZE_INTELLIGENCE: 'INITIALIZE_INTELLIGENCE',
  OPTIMIZE_LANDMARKS: 'OPTIMIZE_LANDMARKS',
  UPDATE_RIR_RECOMMENDATIONS: 'UPDATE_RIR_RECOMMENDATIONS',
  
  // Data management
  EXPORT_DATA: 'EXPORT_DATA',
  IMPORT_DATA: 'IMPORT_DATA',
  CREATE_BACKUP: 'CREATE_BACKUP',
  
  // UI actions
  SET_ACTIVE_PHASE: 'SET_ACTIVE_PHASE',
  SET_VIEW: 'SET_VIEW',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  
  // Generic actions
  UPDATE_STATE: 'UPDATE_STATE',
  RESET_STATE: 'RESET_STATE'
};
