// App Context Action Types
export const APP_ACTIONS = {
    // User actions
    SET_USER: 'SET_USER',
    CLEAR_USER: 'CLEAR_USER',

    // Assessment actions
    UPDATE_ASSESSMENT: 'UPDATE_ASSESSMENT',
    SET_ASSESSMENT: 'SET_ASSESSMENT',
    CLEAR_ASSESSMENT: 'CLEAR_ASSESSMENT',

    // Overload assessment actions
    UPDATE_OVERLOAD: 'UPDATE_OVERLOAD',
    SET_OVERLOAD: 'SET_OVERLOAD',
    CLEAR_OVERLOAD: 'CLEAR_OVERLOAD',

    // Fatigue assessment actions
    UPDATE_FATIGUE: 'UPDATE_FATIGUE',
    SET_FATIGUE: 'SET_FATIGUE',
    CLEAR_FATIGUE: 'CLEAR_FATIGUE',

    // Volume landmarks actions
    UPDATE_VOLUME_LANDMARKS: 'UPDATE_VOLUME_LANDMARKS',
    SET_VOLUME_LANDMARKS: 'SET_VOLUME_LANDMARKS',
    CLEAR_VOLUME_LANDMARKS: 'CLEAR_VOLUME_LANDMARKS',

    // Mesocycle integration actions
    UPDATE_MESOCYCLE: 'UPDATE_MESOCYCLE',
    SET_MESOCYCLE: 'SET_MESOCYCLE',
    CLEAR_MESOCYCLE: 'CLEAR_MESOCYCLE',

    // Program actions
    SAVE_PROGRAM: 'SAVE_PROGRAM',
    UPDATE_PROGRAM: 'UPDATE_PROGRAM',
    CLEAR_PROGRAM: 'CLEAR_PROGRAM',

    // Timeline actions
    SET_TIMELINE: 'SET_TIMELINE',
    ADD_TIMELINE_EVENT: 'ADD_TIMELINE_EVENT',
    UPDATE_TIMELINE_EVENT: 'UPDATE_TIMELINE_EVENT',
    REMOVE_TIMELINE_EVENT: 'REMOVE_TIMELINE_EVENT',
    CLEAR_TIMELINE: 'CLEAR_TIMELINE',

    // Loading states
    SET_LOADING: 'SET_LOADING',
    CLEAR_LOADING: 'CLEAR_LOADING',

    // Error handling
    SET_ERROR: 'SET_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',

    // Auth redirect
    SET_AUTH_REDIRECT_NEEDED: 'SET_AUTH_REDIRECT_NEEDED'
};
