// Expanded catalog with equipment tags & rep schemes (6-10 per category where possible)
export const AssistanceCatalog = {
    push: [
        { id: "db_bench", name: "DB Bench Press", equip: ["db"], sets: 5, reps: "10-15" },
        { id: "incline_db", name: "Incline DB Press", equip: ["db"], sets: 5, reps: "10-15" },
        { id: "ohp_db", name: "DB Overhead Press", equip: ["db"], sets: 5, reps: "10-12" },
        { id: "cg_bench", name: "Close-Grip Bench", equip: ["bb"], sets: 5, reps: "8-12" },
        { id: "dips", name: "Dips", equip: ["bw", "dip"], sets: 5, reps: "10-15" },
        { id: "pushups", name: "Push-Ups", equip: ["bw"], sets: 5, reps: "AMRAP" },
        { id: "landmine_press", name: "Landmine Press", equip: ["landmine"], sets: 5, reps: "10-12" },
        { id: "triceps_pd", name: "Triceps Pushdown", equip: ["cable", "band"], sets: 5, reps: "12-15" },
        { id: "db_fly", name: "DB Fly", equip: ["db", "bench"], sets: 3, reps: "10-15" },
        { id: "push_press", name: "Push Press", equip: ["bb"], sets: 3, reps: "5-8" },
        { id: "front_raise", name: "Plate Front Raise", equip: ["plate"], sets: 3, reps: "12-15" },
    ],
    pull: [
        { id: "chinups", name: "Chin-Ups", equip: ["bw", "bar"], sets: 5, reps: "AMRAP" },
        { id: "pullups", name: "Pull-Ups", equip: ["bw", "bar"], sets: 5, reps: "AMRAP" },
        { id: "inv_row", name: "Inverted Row", equip: ["bw", "rings"], sets: 5, reps: "AMRAP" },
        { id: "db_row", name: "DB Row", equip: ["db"], sets: 5, reps: "10-12" },
        { id: "bb_row", name: "Barbell Row", equip: ["bb"], sets: 5, reps: "8-12" },
        { id: "face_pull", name: "Face Pull", equip: ["cable", "band"], sets: 5, reps: "12-20" },
        { id: "lat_pulldown", name: "Lat Pulldown", equip: ["machine", "cable"], sets: 5, reps: "10-12" },
        { id: "csr", name: "Chest-Supported Row", equip: ["machine", "db"], sets: 5, reps: "10-12" },
        { id: "t_bar_row", name: "T-Bar Row", equip: ["machine"], sets: 4, reps: "8-12" },
        { id: "seated_cable_row", name: "Seated Cable Row", equip: ["cable", "machine"], sets: 4, reps: "10-12" },
        { id: "hammer_curl", name: "Hammer Curl", equip: ["db"], sets: 3, reps: "10-15" },
        { id: "bb_curl", name: "Barbell Curl", equip: ["bb"], sets: 3, reps: "8-12" },
    ],
    singleLeg: [
        { id: "db_split_squat", name: "DB Split Squat", equip: ["db"], sets: 3, reps: "10-12" },
        { id: "rfess", name: "Bulgarian Split Squat", equip: ["db"], sets: 3, reps: "10-12" },
        { id: "db_lunge", name: "DB Walking Lunge", equip: ["db"], sets: 3, reps: "10-12/leg" },
        { id: "stepup", name: "DB Step-Up", equip: ["db", "box"], sets: 3, reps: "8-12/leg" },
        { id: "rev_lunge", name: "Reverse Lunge", equip: ["db"], sets: 3, reps: "10-12/leg" },
        { id: "pistol_box", name: "Box Pistol (assisted)", equip: ["bw"], sets: 3, reps: "6-10/leg" },
        { id: "walking_lunge_bw", name: "Walking Lunge (BW)", equip: ["bw"], sets: 3, reps: "12-20/leg" },
        { id: "cossack_squat", name: "Cossack Squat", equip: ["bw"], sets: 3, reps: "8-12/side" },
    ],
    posterior: [
        { id: "back_ext", name: "Back Extension", equip: ["machine", "bw"], sets: 3, reps: "10-15" },
        { id: "ghr", name: "Glute-Ham Raise", equip: ["machine"], sets: 3, reps: "8-12" },
        { id: "rdl_bb", name: "Romanian Deadlift", equip: ["bb"], sets: 3, reps: "8-10" },
        { id: "rdl_db", name: "DB Romanian Deadlift", equip: ["db"], sets: 3, reps: "10-12" },
        { id: "good_morning", name: "Good Morning", equip: ["bb"], sets: 3, reps: "8-10" },
        { id: "hip_thrust", name: "Hip Thrust", equip: ["bb", "bench"], sets: 3, reps: "8-12" },
        { id: "leg_curl", name: "Leg Curl", equip: ["machine"], sets: 3, reps: "10-15" },
        { id: "kb_swing", name: "KB Swing", equip: ["kb"], sets: 3, reps: "15-20" },
        { id: "reverse_hyper", name: "Reverse Hyper", equip: ["machine"], sets: 3, reps: "10-15" },
        { id: "good_morning_ssb", name: "SSB Good Morning", equip: ["bb"], sets: 3, reps: "8-10" },
        { id: "glute_bridge", name: "Glute Bridge", equip: ["bw"], sets: 3, reps: "12-15" },
    ],
    core: [
        { id: "hkr", name: "Hanging Knee Raise", equip: ["bw", "bar"], sets: 3, reps: "10-15" },
        { id: "hlr", name: "Hanging Leg Raise", equip: ["bw", "bar"], sets: 3, reps: "8-12" },
        { id: "ab_wheel", name: "Ab Wheel", equip: ["bw", "abwheel"], sets: 3, reps: "8-15" },
        { id: "plank", name: "Plank", equip: ["bw"], sets: 3, reps: "45-75s" },
        { id: "side_plank", name: "Side Plank", equip: ["bw"], sets: 3, reps: "30-60s/side" },
        { id: "cable_crunch", name: "Cable Crunch", equip: ["cable"], sets: 3, reps: "12-15" },
        { id: "pallof", name: "Pallof Press", equip: ["cable", "band"], sets: 3, reps: "10-15/side" },
        { id: "weighted_situp", name: "Weighted Sit-Up", equip: ["plate"], sets: 3, reps: "10-15" },
        { id: "hanging_windshield", name: "Hanging Windshield Wiper", equip: ["bw", "bar"], sets: 3, reps: "6-10/side" },
        { id: "stir_pot", name: "Stir the Pot", equip: ["ball"], sets: 3, reps: "8-12/dir" },
        { id: "farmer_carry", name: "Farmer Carry", equip: ["db"], sets: 4, reps: "30-40m" },
    ],
};

export default AssistanceCatalog;
