// App Context Action Types
export const APP_ACTIONS = {
  // User actions
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  
  // Assessment actions
  UPDATE_ASSESSMENT: 'UPDATE_ASSESSMENT',
  SET_ASSESSMENT: 'SET_ASSESSMENT',
  CLEAR_ASSESSMENT: 'CLEAR_ASSESSMENT',
  
  // Program actions
  SAVE_PROGRAM: 'SAVE_PROGRAM',
  UPDATE_PROGRAM: 'UPDATE_PROGRAM',
  CLEAR_PROGRAM: 'CLEAR_PROGRAM',
  
  // Timeline actions
  SET_TIMELINE: 'SET_TIMELINE',
  ADD_TIMELINE_EVENT: 'ADD_TIMELINE_EVENT',
  UPDATE_TIMELINE_EVENT: 'UPDATE_TIMELINE_EVENT',
  REMOVE_TIMELINE_EVENT: 'REMOVE_TIMELINE_EVENT',
  CLEAR_TIMELINE: 'CLEAR_TIMELINE',
  
  // Loading states
  SET_LOADING: 'SET_LOADING',
  CLEAR_LOADING: 'CLEAR_LOADING',
  
  // Error handling
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};
