name: CI with E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Install dependencies (React app)
        working-directory: ./tracker-ui
        run: pnpm install
        
      - name: Install Playwright browsers
        working-directory: ./tracker-ui
        run: npx playwright install --with-deps
        
      - name: Strict lint React app (fail on warnings)
        working-directory: ./tracker-ui
        run: pnpm run lint:ci
        
      - name: Run unit tests with coverage
        working-directory: ./tracker-ui
        run: pnpm run test:unit
        
      - name: Build React app
        working-directory: ./tracker-ui
        run: pnpm run build
        
      - name: Run E2E tests
        working-directory: ./tracker-ui
        run: pnpm run test:e2e
        
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tracker-ui/playwright-report/
          retention-days: 30
